# Generated by Django 5.0.6 on 2024-06-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_user_message_customer_message_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='message',
            name='seller',
        ),
    ]
